server:
   port: 8888

spring:
#   profiles:
#      active: native
   cloud:
      config:
         server:
            git:
               uri: https://github.com/ederson-lehugeur/microservices-repository-config
               default-label: main
               search-paths: fornecedor
#            native:
#               search-locations: D:/Projects/eclipse-workspace/microservices/microservices-repository-config
